# Generated by Django 3.2.6 on 2022-07-06 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_rename_passengers_passenger'),
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checks', models.BooleanField(default=True)),
            ],
        ),
    ]
