# Generated by Django 3.2.20 on 2023-07-18 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0006_remove_flight_destination'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='origin',
        ),
        migrations.AddField(
            model_name='flight',
            name='origins',
            field=models.ManyToManyField(to='flights.Airport'),
        ),
    ]
